name: aeneas
favicon: null
layout_spectrum: 0.7438984978944063
typography_spectrum: 0.51102
title: '12345'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#10143d'
    - '#252e63'
    - '#000000'
    - '#230ab7'
    - '#461d72'
  brandStrength: 0.25
  lightness: 0.1875
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
